### ISSUE TITLE
Dernières questions

### ISSUE THREAD

**Issue by TeoBernier** [julibinho/VDJ-Kernel#1]
Ce sont les dernières questions que j'ai, merci infiniment pour votre temps et votre rapidité !

`Peut-tu comptes combien de cas ont ce "_", si ils sont pas nombreux on peut les enlever pour l'instant`
Il y en a 12 au total, je les déplacerai en fin de fichier

`IGHV3-43D*03 c'est le même que IGHV3-43D*01`
Ainsi, IGHV3-43, IGHV3-43D et IGHV3-47 sont différents les uns des autres ?

`Le problème des alignements est que ça peut être très lent, rappelez-vous que c' est une simulation, les vrais données ont plus d' un million de séquences. `
Combien de temps prends votre algorithme / Quelle limite de temps faudrait il atteindre par séquence ?

Sinon, vraiment merci pour toutes vos réponses !

**Comment by julibinho** [comment]
**Il y en a 12 au total, je les déplacerai en fin de fichier**
On peut les enlever pour l'instant

**Ainsi, IGHV3-43, IGHV3-43D et IGHV3-47 sont différents les uns des autres ?**
Je crois qui oui, a confirmer avec @NikaAb 

**Combien de temps prends votre algorithme / Quelle limite de temps faudrait il atteindre par séquence ?**
Le plus performant, c'est IMGT, il y a seulement un serveur web, parfois on attents des jours pour avoir la reponse ça dependent de combien de personnes sont devant nous.
Je dira que si on arrive à analyser un repertoire immunaire 1 million de sequence en mois d'une heure c'est assez bien

**Comment by TeoBernier** [comment]
Vous voulez que je mette ce que j'ai fait en Rust dans le git ? 

J'ai mis ça dans un git à part en attendant, mais comme vous voulez !

**Comment by julibinho** [comment]
ah vous de voir, si vous voulez travailler un peu plus et mettre un code plus clean dans notre git, ça marche aussi :-)

**Comment by TeoBernier** [comment]
Ok, je vais clean le code et je le mettrai après, avec pleins de commentaires ! 

Sinon, 1M en 1 heure, ça me semble faisable sans trop de problème en optimisant un peu (j'ai vraiment fait une implémentation naïve) !

Vous pouvez fermer l'issue si vous n'avez rien à rajouter ! Merci encore !
