### ISSUE TITLE
Comment les résultats sont-ils calculés ?

### ISSUE THREAD

**Issue by TeoBernier** [julibinho/VDJ-Kernel#2]
Bonjour 😄 

J'ai donc fait un peu de formatage dans mon output afin d'avoir un truc clean : 

* La 1ère ligne représente le gène V choisi, la 2ème le gène D et la 3ème, le gène J. 
* Le -[22]- nous indique qu'un des 3 gènes couvre à lui seul, parfaitement, une suite de 22 nucléotides (pas de mutation, pas de décalage, pas de superposition avec les autres gènes).

```
Sequence : S10
g-[22]-a-[11]-a-[8]-g-[45]-aaccactacac-[7]-g-[16]-aaaggga-[19]-gtagtggtaatagtggttacac-[21]-a-[20]-g-[73]-tgagagtctgccgtgggagttactcc-[42]

Predictions :
g-[22]-a-[11]-a-[8]-g-[45]-aaccactacac-[7]-g-[16]-gaaggga-[19]-gtagtggtaatagtggttacac-[21]-a-[20]-g-[73]-tgaaa.....................-[42]
.-[22]-.-[11]-.-[8]-.-[45]-...........-[7]-.-[16]-.......-[19]-......................-[21]-.-[20]-.-[73]-..ag.gtatgtagtgggagttactcc-[42]
.-[22]-.-[11]-.-[8]-.-[45]-...........-[7]-.-[16]-.......-[19]-......................-[21]-.-[20]-.-[73]-......................ctac-[42]


Results :
.-[22]-g-[11]-.-[8]-a-[45]-gactactacat-[7]-a-[16]-gaagggg-[19]-ttagtagtagtagtagttacac-[21]-g-[20]-a-[73]-cgagag....................-[42]
.-[22]-.-[11]-.-[8]-.-[45]-...........-[7]-.-[16]-.......-[19]-.....ggt.atagtgggtacac-[21]-.-[20]-.-[73]-..........................-[42]
.-[22]-.-[11]-.-[8]-.-[45]-...........-[7]-.-[16]-.......-[19]-......................-[21]-.-[20]-.-[73]-......................ctac-[42]
```

On voit ici que l'algorithme d'alignement aligne bizarrement le gène D du résultat (le problème ici est que je cherche à l'aligner sur la séquence entière, et pas qu'à la fin où il devrait normalement être..., donc je l'aligne en superposition avec le gène V...)

En revanche, le choix que fait mon algorithme, rien qu'en terme de nucléotides, à l'air beaucoup plus approprié non ? Est-ce normal ?

**Comment by julibinho** [comment]
Bonjour,

Merci pour ces résultats, vous pouvez compter %V, %d et %J qui était correctement prédit?
On se parle mardi?
Est-ce que ça peut être avant 16h?

Merci et bon dimanche

**Comment by TeoBernier** [comment]
J'ai cours de 14h à 16h donc avant 16h reviendra à avant 14h sinon, à partir de 16h pile.

Sinon je n'ai pas très bien compris, vous voulez que je compte le pourcentage de V, D, et J, que mon algorithme prédit, identique à la solution ? (Sans prendre en compte les allèles ?)

Merci, bon dimanche à vous aussi !

**Comment by julibinho** [comment]
Oui, c'est ça.

**Comment by Magicdjez** [comment]
j'ai cours jusque'a 18h mardi

**Comment by julibinho** [comment]
Et A13:30?

**Comment by Magicdjez** [comment]
Je reprend les cours a 14h mais j'ai une pause à partir de 12h30 ca dépend combien ça va durer

**Comment by TeoBernier** [comment]
Du coup prévenez-moi à l'avance pour la date, je suis dispo quand vous voulez.

Sinon, j'ai upload le fichier `accuracy_most_chose.txt`, il contient tous les gènes que je suis censé prédire, et les gènes que je prédis le plus pour chacun d'entre eux. Je mets aussi la fréquence de prédiction (en %) de ce gène (qui du coup est la fréquence la plus élevée).
```
Result :                         [  D2-15,   D2-8, D2/OR15-2a,      D3-10,      D3-16,      D3-22,    J3]
Most Predict :                   [   D6-6,   D2-8,       D2-2,      D3-10,      D3-16,      D3-22,    J3]
Percentage of 'most predict'  :  [     26,     84,         87,         49,         55,         42,    77]
```
On voit que ceux-là ne sont pas super (j'ai pris les pires), mais les autres ont tous bien été deviné !

Il faudra que je rajoute un système de bornes inf et sup comme limite pour l'alignement et ça marchera nickel !

**Comment by julibinho** [comment]
Bonjour,
on va essayer 13:30, et on va voir ensemble un autre creanaux pour les reunions, mardi apres 16 je ne peux pas.
Merci et à demain
voici le lien
Join Zoom Meeting
https://zoom.us/j/91916479977?pwd=SlVqNFZRNzR1Ui9DYUdiT2FEQ1Vqdz09

Meeting ID: 919 1647 9977
Passcode: 99x7vk

**Comment by TeoBernier** [comment]
J'ai fait un emploi du temps un peu à l'arrache, remplissez vos contraintes / où vous ne voulez pas avec des 1, et ça merge les disponibilités automatiquement : https://docs.google.com/spreadsheets/d/1uJghmxbdoUCRvDfe6wA_7u5E_D4fmf_z5SOVzPp-hic/edit?usp=sharing

**Comment by TeoBernier** [comment]
Alors j'ai eu une idée cette nuit, l'algo bat toutes les versions précédentes ! Toujours aussi précis (voire même un peu plus) et bien plus rapide ! (D'après les estimations, 4600 secondes (~1h20) pour faire 1 million de séquences, sans parallélisme, ni rien). 

Mais il y a encore clairement la place à l'optimisation ! 
Et en plus si on rajoute des filtres (k mers et etc...) ! 

J'ai aussi préparé une feature que j'implémenterai bientôt (si on a pas besoin de connaître l'allèle précisément), afin de fusionner les allèles en un seul gène, pour avoir moins de gènes à tester.

Sur ce, je vais dormir un peu avant 13h30 !

N'hésitez pas à remplir le planning, ça nous aidera sûrement pour vite fait regarder pendant la réunion !
